### ISSUE TITLE
ci: flaky tests

### ISSUE THREAD

**Issue by skuruppu** [cloudspannerecosystem/python-spanner-sqlalchemy#72]
## Expected Behavior
Test suite should pass against prod.

## Actual Behavior
We see lots of different kinds of errors. Examples:
 - "Transaction aborted. Database schema probably changed during transaction, retry may succeed." [link](https://app.circleci.com/pipelines/github/cloudspannerecosystem/python-spanner-sqlalchemy/217/workflows/473e8528-3cb2-4b01-afe2-5104c4d94af4/jobs/254)
 - Same as above except also with "InvalidArgument: 400 Column x is not present in table some_table [at 1:29]\nINSERT INTO some_table (id, x, y) VALUES (@a0, @a1, @a2)\n" [link](https://app.circleci.com/pipelines/github/cloudspannerecosystem/python-spanner-sqlalchemy/214/workflows/ac1ac712-3b9f-401a-831a-1ba2a59de214/jobs/250)
 - Migration tests seem to be passing but there is always an error "Transaction is already committed" [link](https://app.circleci.com/pipelines/github/cloudspannerecosystem/python-spanner-sqlalchemy/217/workflows/473e8528-3cb2-4b01-afe2-5104c4d94af4/jobs/254)
 - "FailedPrecondition: 400 Duplicate name in schema: noncol_idx_test_nopk" [link](https://app.circleci.com/pipelines/github/cloudspannerecosystem/python-spanner-sqlalchemy/217/workflows/473e8528-3cb2-4b01-afe2-5104c4d94af4/jobs/253)

## Steps to Reproduce the Problem

1. Create a PR and allow the CircleCI workflow to run.

**Comment by IlyaFaer** [comment]
The first error seems familiar, I think it's already fixed by this PR: https://github.com/googleapis/python-spanner/pull/345
I'll keep an eye on it, but after #345 was merged, I didn't get single `Aborted` failure yet.

`Column not present` and `Duplicate name` most likely happening because someone executing the tests locally, in the same time the workflow do. I assume the PR #65 is not working fine, because we have a config tweaked for the concrete instance and database here:
https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/blob/092e6d874cb22daff350296e6c61b29aafc1f95a/setup.cfg#L29

Migrations - yeah, I also see this. There was an attempt to fix the similar error, but looks like it's not fixed yet:
https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/pull/68

Okay, working on them.

**Comment by IlyaFaer** [comment]
These errors seem to be fixed, closing the issue, but will keep an eye.
